# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty

# Setup
title:               LineaVita
tagline:             'A bring your own storage social media system.'
description:         'LineaVita is a simple social media application that has no advertisements.  It is based on utilizing storage provided by users.'
url:                 'http://lineavita.github.io'
repo:				 'http://github.com/LineaVita/Vita'
baseurl:             'https://lineavita.github.io'
paginate:            5

# About/contact
author:
  name:              Brian Nelson
  url:               https://twitter.com/brian_e_nelson
  
# Custom vars
version:             0.7.0
